# Generated by Django 5.2.6 on 2025-10-12 19:16

import django.db.models.deletion
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_comment_article_comments_favorite_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='excerpt',
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', mdeditor.fields.MDTextField(verbose_name='Содержание')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Номер версии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания версии')),
                ('change_reason', models.CharField(blank=True, max_length=500, verbose_name='Причина изменений')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Черновик версии')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='docs.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор версии')),
            ],
            options={
                'verbose_name': 'Версия статьи',
                'verbose_name_plural': 'Версии статей',
                'ordering': ['-version_number'],
                'unique_together': {('article', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_article', to='docs.articleversion', verbose_name='Текущая версия'),
        ),
    ]
