# Generated by Django 5.2.6 on 2025-10-14 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_remove_article_content_remove_article_excerpt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('txt', 'Plain Text')], max_length=10, verbose_name='Формат экспорта')),
                ('exported_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата экспорта')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='docs.article', verbose_name='Статья')),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Экспортировал')),
            ],
            options={
                'verbose_name': 'Экспорт статьи',
                'verbose_name_plural': 'Экспорты статей',
                'ordering': ['-exported_at'],
            },
        ),
    ]
