# Generated by Django 5.2.6 on 2025-10-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_articleexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.CharField(choices=[('public', 'Публичная'), ('private', 'Приватная')], default='public', max_length=10, verbose_name='Видимость'),
        ),
    ]
