# Generated by Django 5.2.6 on 2025-10-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_article_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='visibility',
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('private', 'Приватный'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', max_length=10, verbose_name='Статус'),
        ),
    ]
